/**
 * Knetik Platform API Documentation latest 
 * This is the spec for the Knetik API.  Use this in conjunction with the documentation found at https://knetikcloud.com.
 *
 * OpenAPI spec version: latest 
 * Contact: support@knetik.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.knetikcloud.client.model


case class BreRuleLog (
  /* Whether the rule ran */
  ran: Option[Boolean],
  /* The reason for the rule */
  reason: Option[String],
  /* The end date of the rule in seconds */
  ruleEndDate: Option[Long],
  /* The id of the rule */
  ruleId: Option[String],
  /* The name of the rule */
  ruleName: Option[String],
  /* The start date of the rule in seconds */
  ruleStartDate: Option[Long]
)

