/**
 * Knetik Platform API Documentation latest 
 * This is the spec for the Knetik API.  Use this in conjunction with the documentation found at https://knetikcloud.com
 *
 * OpenAPI spec version: latest 
 * Contact: support@knetik.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.knetikcloud.client.model


case class CategoryResource (
  /* Whether the category is currently active. If not, it and its questions will be filtered out. */
  active: Option[Boolean],
  /* A map of additional properties, keyed on the property name.  Must match the names and types defined in the template for this item type */
  additionalProperties: Option[Map[String, Property]],
  /* The unique ID for this category */
  id: Option[String],
  /* The name of this category. Cannot be blank */
  name: String,
  /* A category template this category is validated against (private). May be null and no validation of additional_properties will be done */
  template: Option[String]
)

