/**
 * Knetik Platform API Documentation latest 
 * This is the spec for the Knetik API.  Use this in conjunction with the documentation found at https://knetikcloud.com.
 *
 * OpenAPI spec version: latest 
 * Contact: support@knetik.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.knetikcloud.client.model


case class CoreActivitySettings (
  /* Whether the host can boot a user while the status is PLAYING. Default false */
  bootInPlay: Option[Boolean],
  /* Restriction for whether the host creating an occurrence can specify a custom launch address (such as their own ip address). Default 'false' */
  customLaunchAddressAllowed: Option[Boolean],
  /* Restriction for who can host an occurrence. admin disallows regular users, player means the user must also be a player in the occurrence if not admin, non-player means the user has the option to host without being a player. Default 'player' */
  hostOption: Option[String],
  /* Restriction for whether the host has control of the status once the game launches. If false they can only manage the game before (when setup and open). Default 'false' */
  hostStatusControl: Option[Boolean],
  /* Whether users can join while the status is PLAYING. Default false */
  joinInPlay: Option[Boolean],
  /* Whether users can leave while the status is PLAYING. Default false */
  leaveInPlay: Option[Boolean],
  /* The maximum number of players the game can hold */
  maxPlayers: Option[Integer],
  /* The minimum number of players the game can hold */
  minPlayers: Option[Integer],
  /* Restriction for who is able to report game end and results. Admin is always able to send results as well. Default 'none' */
  resultsTrust: Option[String]
)

