/**
 * Knetik Platform API Documentation latest 
 * This is the spec for the Knetik API.  Use this in conjunction with the documentation found at https://knetikcloud.com.
 *
 * OpenAPI spec version: latest 
 * Contact: support@knetik.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.knetikcloud.client.model


case class CountryResource (
  /* The iso2 of the country */
  iso2: Option[String],
  /* The iso3 of the country */
  iso3: Option[String],
  /* The name of the country resource */
  name: Option[String]
)

