/**
 * Knetik Platform API Documentation latest 
 * This is the spec for the Knetik API.  Use this in conjunction with the documentation found at https://knetikcloud.com.
 *
 * OpenAPI spec version: latest 
 * Contact: support@knetik.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.knetikcloud.client.model


case class CreateActivityOccurrenceRequest (
  /* The id of the activity, only needed when outside of challenge/event */
  activityId: Option[Long],
  /* The id of the challenge activity (required if playing in a challenge/event). Note that this is the challenge_activity_id in case the same activity apears twice in the challenge. */
  challengeActivityId: Option[Long],
  /* The entitlement item required to enter the occurrence. Required if not part of an event. Must come from the set of entitlement items listed in the activity */
  entitlement: Option[ItemIdRequest],
  /* The id of the event this occurence is a part of, if any */
  eventId: Option[Long],
  /* The values selected from the available settings defined for the activity. Ex: difficulty: hard. Can be left out if the activity is played during an event and the settings are already set at the event level. Ex: every monday, difficulty: hard, number of questions: 10, category: sport. Otherwise, the set must exactly match those of the activity. */
  settings: Option[List[SelectedSettingRequest]],
  /* Whether this occurrence will be ran as a simulation. Simulations will not be rewarded. Useful for bot play or trials */
  simulated: Option[Boolean],
  /* The current status of the occurrence (default: SETUP). */
  status: Option[String],
  /* The list of users participating in this occurrence. Can only be set directly with ACTIVITIES_ADMIN permission */
  users: Option[List[Participant]]
)

