/**
 * Knetik Platform API Documentation latest 
 * This is the spec for the Knetik API.  Use this in conjunction with the documentation found at https://knetikcloud.com.
 *
 * OpenAPI spec version: latest 
 * Contact: support@knetik.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.knetikcloud.client.model


case class InvoiceItemResource (
  bundleSku: Option[String],
  currentFulfillmentStatus: Option[String],
  id: Option[Integer],
  invoiceId: Option[Integer],
  itemId: Option[Integer],
  itemName: Option[String],
  originalTotalPrice: Option[Number],
  originalUnitPrice: Option[Number],
  qty: Option[Integer],
  saleName: Option[String],
  sku: Option[String],
  skuDescription: Option[String],
  systemPrice: Option[Number],
  totalPrice: Option[Number],
  typeHint: Option[String],
  unitPrice: Option[Number]
)

