/**
 * Knetik Platform API Documentation latest 
 * This is the spec for the Knetik API.  Use this in conjunction with the documentation found at https://knetikcloud.com
 *
 * OpenAPI spec version: latest 
 * Contact: support@knetik.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.knetikcloud.client.model


case class PropertyFieldResource (
  /* A description of the field */
  description: Option[String],
  /* The type of values within a 'list' type field */
  innerType: Option[String],
  /* A description of fields within objects within a 'list' type field, when inner_type is 'object' */
  innerTypeFields: Option[List[PropertyFieldResource]],
  /* The name of the field */
  name: Option[String],
  /* Whether the field is required */
  required: Option[Boolean],
  /* The type of the field */
  _type: Option[String],
  /* A list of valid values for 'enum' type fields */
  validValues: Option[List[String]]
)

