/**
 * Knetik Platform API Documentation latest 
 * This is the spec for the Knetik API.  Use this in conjunction with the documentation found at https://knetikcloud.com
 *
 * OpenAPI spec version: latest 
 * Contact: support@knetik.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.knetikcloud.client.model


case class TimePeriodUsable (
  description: Option[String],
  /* Used for polymorphic type recognition and thus must match an expected type with additional properties */
  typeHint: Option[String],
  /* The amount of times it can be used */
  maxUse: Option[Integer],
  /* The length of time */
  timeLength: Option[Integer],
  /* The unit of time */
  unitOfTime: Option[String]
)

