/**
 * Knetik Platform API Documentation latest 
 * This is the spec for the Knetik API.  Use this in conjunction with the documentation found at https://knetikcloud.com.
 *
 * OpenAPI spec version: latest 
 * Contact: support@knetik.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.knetikcloud.client.model


case class Topic (
  createdDate: Option[Long],
  displayName: Option[String],
  id: Option[String],
  locked: Option[Boolean],
  tags: Option[List[String]],
  topicMap: Option[Any],
  updatedDate: Option[Long],
  userCount: Option[Integer]
)

