/**
 * Knetik Platform API Documentation latest 
 * This is the spec for the Knetik API.  Use this in conjunction with the documentation found at https://knetikcloud.com.
 *
 * OpenAPI spec version: latest 
 * Contact: support@knetik.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.knetikcloud.client.model


case class UserResource (
  /* A map of additional properties, keyed on the property name (private). Must match the names and types defined in the template for this user type, or be an extra not from the template */
  additionalProperties: Option[Map[String, Property]],
  /* The first line of the user's address (private) */
  address: Option[String],
  /* The second line of user's address (private) */
  address2: Option[String],
  /* The url of the user's avatar image */
  avatarUrl: Option[String],
  /* Relationships where this user is the parent. Read-Only, manage through separate endpoints */
  children: Option[List[UserRelationshipReferenceResource]],
  /* The user's city (private) */
  city: Option[String],
  /* The ISO3 code for the country from the user's address (private). Will be filled in based on GeoIP country at registration if not provided. */
  countryCode: Option[String],
  /* The code for the user's real money currency (private) */
  currencyCode: Option[String],
  /* The user's date of birth (private) as a unix timestamp */
  dateOfBirth: Option[Long],
  /* The user's self description (private) */
  description: Option[String],
  /* The chosen display name of the user, defaults to username if not present */
  displayName: Option[String],
  /* The user's email address (private). May be required and/or unique depending on system configuration (both on by default). Must match standard email requirements if provided (RFC 2822) */
  email: String,
  /* The user's first name (private) */
  firstName: Option[String],
  /* The user's full name (private) */
  fullname: Option[String],
  /* The user's gender (private) */
  gender: Option[String],
  /* The id of the user */
  id: Option[Integer],
  /* The ISO3 code for the user's currency (private) */
  languageCode: Option[String],
  /* The date the user last interacted with the API (private) */
  lastActivity: Option[Long],
  /* The user's last name (private) */
  lastName: Option[String],
  /* The date the user's info was last updated as a unix timestamp */
  lastUpdated: Option[Long],
  /* The user's date of registration as a unix timestamp */
  memberSince: Option[Long],
  /* The user's mobile phone number (private) */
  mobileNumber: Option[String],
  /* Relationships where this user is the child. Read-Only, manage through separate endpoints */
  parents: Option[List[UserRelationshipReferenceResource]],
  /* The plain text password for the new user account. Required for registration; ignored on profile update.  Use password specific endpoints for editing */
  password: Option[String],
  /* The user's postal code (private) */
  postalCode: Option[String],
  /* The user's state (private) */
  state: Option[String],
  /* Tags on the user. Can only be set by admin. Max length per tag is 64 characters */
  tags: Option[List[String]],
  /* A user template this user is validated against (private). May be null and no validation of properties will be done */
  template: Option[String],
  /* The code for the user's timezone (private) */
  timezoneCode: Option[String],
  /* The login username for the user (private). May be set to match email if system does not require usernames separately. */
  username: String
)

