/**
 * Knetik Platform API Documentation latest 
 * This is the spec for the Knetik API.  Use this in conjunction with the documentation found at https://knetikcloud.com.
 *
 * OpenAPI spec version: latest 
 * Contact: support@knetik.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.knetikcloud.client.model


case class VendorResource (
  /* Whether the vendor is active.  Default = true */
  active: Option[Boolean],
  /* A map of additional properties, keyed on the property name (private). Must match the names and types defined in the template for this user type, or be an extra not from the template */
  additionalProperties: Option[Map[String, Property]],
  /* The date the vendor was added. Unix timestamp in seconds */
  createDate: Option[Long],
  /* A description of the vendor */
  description: Option[String],
  /* The id of the vendor */
  id: Option[Integer],
  /* The url of an image for the vendor */
  imageUrl: Option[String],
  /* Whether the vendor needs to manually approve invoices before they are paid.  A separate checkout flow is required in this case.  Default: false */
  manualApproval: Option[Boolean],
  /* The name of the vendor */
  name: String,
  /* The primary email address for the vendor */
  primaryContactEmail: Option[String],
  /* The name of the primary contact for the vendor */
  primaryContactName: Option[String],
  /* The primary phone number for the vendor */
  primaryContactPhone: Option[String],
  /* The email address for sale inquiries for the vendor */
  salesEmail: Option[String],
  /* The email address for support inquiries for the vendor */
  supportEmail: Option[String],
  /* A user template this user is validated against (private). May be null and no validation of properties will be done */
  template: Option[String],
  /* The date the vendor was last updated. Unix timestamp in seconds */
  updateDate: Option[Long],
  /* The url for the vendor's site */
  url: Option[String]
)

