/**
 * Knetik Platform API Documentation latest 
 * This is the spec for the Knetik API.  Use this in conjunction with the documentation found at https://knetikcloud.com
 *
 * OpenAPI spec version: latest 
 * Contact: support@knetik.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model


case class ActivityOccurrenceResource (
  /* The id of the activity */
  activityId: Long,
  /* The id of the challenge activity (as part of the event, required if eventId set) */
  challengeActivityId: Long,
  /* The date this occurrence was created, unix timestamp in seconds */
  createdDate: Long,
  /* The entitlement item required to enter the occurrence. Required if not part of an event. Must come from the set of entitlement items listed in the activity */
  entitlement: ActivityEntitlementResource,
  /* The id of the event */
  eventId: Long,
  /* The id of the activity occurrence */
  id: Long,
  /* Indicate if the rewards have been given out already */
  rewardStatus: String,
  /* The list of settings and their options available for this activity. Should be null on create if and only if part of an event */
  settings: List[SelectedSettingResource],
  /* Whether this occurrence will be played as a simulation. */
  simulated: Boolean,
  /* The date this occurrence was started, unix timestamp in seconds. null if not yet started */
  startDate: Long,
  /* The current status of the occurrence (default: OPEN) */
  status: String,
  /* The date this occurrence was last updated, unix timestamp in seconds */
  updatedDate: Long,
  /* The list of users playing in this occurrence. Can only be set directly with ACTIVITIES_ADMIN permission */
  users: List[ActivityUserResource]
)
