/**
 * Knetik Platform API Documentation Latest
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: Latest
 * Contact: support@knetik.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model


case class ApplyPaymentRequest (
  /* The id of the local invoice being paid. */
  invoiceId: Integer,
  /* The encoded receipt string from Apple's services. */
  receipt: String,
  /* The id of the specific transaction from Apple's services. */
  transactionId: String
)
