/**
 * Knetik Platform API Documentation Latest
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: Latest
 * Contact: support@knetik.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model


case class BreTriggerParameterDefinition (
  /* The name of the parameter. This is used as the unique identifier of this parameter */
  name: String,
  /* The variable type of this parameter. See Bre Variables endpoint for list */
  _type: String
)
