/**
 * Knetik Platform API Documentation Latest
 * This is the spec for the Knetik API.  Use this in conjunction with the documentation found at https://demo.sandbox.knetikcloud.com
 *
 * OpenAPI spec version: Latest
 * Contact: support@knetik.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model


case class CouponDefinition (
  code: String,
  description: String,
  discountType: String,
  exclusive: Boolean,
  maxDiscount: Double,
  maxQuantity: Integer,
  minCartTotal: Double,
  name: String,
  selfExclusive: Boolean,
  targetItemId: Integer,
  _type: String,
  validForTags: List[String],
  value: Double,
  vendorId: Integer
)
