/**
 * Knetik Platform API Documentation latest 
 * This is the spec for the Knetik API.  Use this in conjunction with the documentation found at https://knetikcloud.com
 *
 * OpenAPI spec version: latest 
 * Contact: support@knetik.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model


case class FlagReportResource (
  /* The context of that resource  */
  context: Option[String],
  /* The context ID of that resource */
  contextId: Option[String],
  /* The date/time this resource was created in seconds since epoch */
  createdDate: Option[Long],
  /* The unique ID for that resource */
  id: Option[Long],
  /* The reason of that resource required only in case of active resolution */
  reason: Option[String],
  /* The resolution of that resource */
  resolution: String,
  /* The date/time this report was resolved in seconds since epoch. Null if not resolved yet */
  resolved: Option[Long],
  /* The date/time this resource was last updated in seconds since epoch */
  updatedDate: Option[Long]
)

