/**
 * Knetik Platform API Documentation latest 
 * This is the spec for the Knetik API.  Use this in conjunction with the documentation found at https://knetikcloud.com
 *
 * OpenAPI spec version: latest 
 * Contact: support@knetik.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model


case class SimpleWallet (
  /* The current balance of the wallet */
  balance: Option[Double],
  /* The ISO currency code for the wallet */
  code: Option[String],
  /* The name of the currency stored in the wallet */
  currencyName: Option[String],
  /* The unique ID of the wallet */
  id: Option[Integer],
  /* The ID of the user to whom the wallet belongs */
  userId: Option[Integer]
)

