/**
 * Knetik Platform API Documentation latest 
 * This is the spec for the Knetik API.  Use this in conjunction with the documentation found at https://knetikcloud.com
 *
 * OpenAPI spec version: latest 
 * Contact: support@knetik.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model


case class UsageInfo (
  /* The number of requests within the range */
  count: Option[Long],
  /* The date at the start of the range (see granularity) */
  date: Option[Long],
  /* The http method */
  method: Option[String],
  /* The url path */
  url: Option[String]
)

